apiVersion: v1
kind: Pod
metadata:
  name: yolo-pod
  labels:
    app: yolo
spec:
  restartPolicy: Never
  containers:
  - name: yolo-container
    image: mfois13/yolo_app:latest
    securityContext:
      privileged: true
    volumeMounts:
    - name: dri-device
      mountPath: /dev/dri
    - name: dfx-socket
      mountPath: /var/run/dfx-mgrd.socket
    - name: dpu-drivers
      mountPath: /lib/firmware/xilinx
    - name: input-images
      mountPath: /input_images
    stdin: true
    tty: true
  volumes:
  - name: dri-device
    hostPath:
      path: /dev/dri
      type: Directory
  - name: dfx-socket
    hostPath:
      path: /var/run/dfx-mgrd.socket
      type: Socket
  - name: dpu-drivers
    hostPath:
      path: /lib/firmware/xilinx
      type: Directory
  - name: input-images
    hostPath:
      path: /home/root/yolo_img
      type: Directory
  nodeSelector:
    role: worker
