apiVersion: v1
kind: Pod
metadata:
  name: aes-axidma-pod
spec:
  restartPolicy: Never
  nodeSelector:
    role: worker

  containers:
    - name: aes-axidma
      image: mfois13/ubuntu_aes_axidma:latest
      imagePullPolicy: Always

      securityContext:
        privileged: true

      volumeMounts:
        - name: fpga0
          mountPath: /dev/fpga0
        - name: axi-dma
          mountPath: /dev/axidma
        - name: host-dev
          mountPath: /host-dev
        - name: host-sys
          mountPath: /sys
        - name: host-configfs
          mountPath: /configfs
        - name: host-firmware
          mountPath: /lib/firmware

      command: ["/bin/sh", "-c"]
      args:
        - |
          set -eu

          fpgautil -R -n full || fpgautil -R || true
          fpgautil -b /aes/aes256_dma.bit
          fpgautil -o /aes/pl_aes.dtbo

          while [ ! -c /host-dev/uniss_dma ]; do sleep 0.2; done
          ln -snf /host-dev/uniss_dma /dev/uniss_dma

          exec /bin/sh -c '/aes/dma_test_aes | pv -L 6k'

      # Finché questa non passa, readiness/liveness non partono e il pod non diventa Ready.
      startupProbe:
        exec:
          command: ["/bin/sh", "-c", "test -c /host-dev/uniss_dma" ]
        periodSeconds: 1
        timeoutSeconds: 1
        failureThreshold: 120   # ~120s di massimo per “startup” (1s * 120)

      # Il pod è Ready solo quando l'alias /dev/uniss_dma esiste ed è un char device.
      readinessProbe:
        exec:
          command: ["/bin/sh", "-c", "test -c /dev/uniss_dma" ]
        periodSeconds: 1
        timeoutSeconds: 1
        failureThreshold: 3

  volumes:
    - name: fpga0
      hostPath:
        path: /dev/fpga0
        type: CharDevice
    - name: axi-dma
      hostPath:
        path: /dev/axidma
    - name: host-dev
      hostPath:
        path: /dev
        type: Directory
    - name: host-sys
      hostPath:
        path: /sys
        type: Directory
    - name: host-configfs
      hostPath:
        path: /sys/kernel/config
        type: Directory
    - name: host-firmware
      hostPath:
        path: /lib/firmware
        type: Directory

