FROM --platform=$TARGETPLATFORM gcc:13 AS build
WORKDIR /src
COPY dma_test_aes.c .
RUN gcc -O2 -Wall -Wextra -o dma_test_aes dma_test_aes.c

FROM mfois13/yocto-axidma-distro:latest
WORKDIR /aes
COPY --from=build /src/dma_test_aes /aes/dma_test_aes
COPY aes256_dma.bit pl_aes.dtbo ./

CMD ["/bin/sh", "-c", "fpgautil -R && fpgautil -b /aes/aes256_dma.bit && fpgautil -o /aes/pl_aes.dtbo && /aes/dma_test_aes"]

